version: "3.8"
services:
  express-app:
    build: .
    container_name: express-app
    networks:
      - app-network
    depends_on:
      - mariadb
    ports:
      - "3000:3000" # Sesuaikan dengan port aplikasi Anda

  mariadb:
    image: mariadb:latest
    container_name: mariadb-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: simpleapi_db
      MYSQL_USER: root
      MYSQL_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - C:\Users\User\projects\docker-app\mariadb:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
