version: "3.8"
services:
  express-app:
    build: .
    container_name: express-app
    depends_on:
      - mariadb
    ports:
      - "3000:3000" # Sesuaikan dengan port aplikasi Anda
  mariadb:
    image: mariadb:latest
    container_name: mariadb-app
    ports:
      - "3306:3306" # Memetakan port 3306 host ke port 3306 di container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword # Password root MariaDB
    volumes:
      - C:\Users\User\projects\docker-app\mariadb:/var/lib/mysql
networks:
  app-network:
    driver: bridge
